sudo: required
dist: trusty
language: generic

env:
  global:
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=ccl-bin  EMACS=26.3
    - LISP=sbcl-bin EMACS=24.5
    - LISP=sbcl-bin EMACS=25.3
    - LISP=sbcl-bin EMACS=26.3

install:
  - wget https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk
  - make EMACS_VERSION=$EMACS -f emacs-travis.mk install_emacs
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - make LISP="ros run -L $LISP" EMACS=$HOME/emacs/$EMACS/src/emacs check

cache:
  directories:
    - "$HOME/emacs/"
    - "$HOME/.roswell/"
